name        : transmission
version     : 2.92
release     : 3
source     :
    - http://download.transmissionbt.com/files/transmission-2.92.tar.xz : 3a8d045c306ad9acb7bf81126939b9594553a388482efa0ec1bfb67b22acd35f
license     : GPL-2.0+
summary     : Lightweight BitTorrent client
builddeps   :
    - pkgconfig(libevent)
    - pkgconfig(gtk+-3.0)
description : |
    Transmission provides a simple and easy to use cross-platform lightweight BitTorrent client
setup      : |
    %configure --with-gtk
build      : |
    %make
install    : |
    %make_install
