name       : transmission
version    : 4.0.3
release    : 21
source     :
    - https://github.com/transmission/transmission/releases/download/4.0.3/transmission-4.0.3.tar.xz : b6b01fd58e42bb14f7aba0253db932ced050fcd2bba5d9f8469d77ddd8ad545a
homepage   : https://transmissionbt.com/
license    : GPL-2.0-or-later
component  : network.download
summary    : Lightweight BitTorrent client
description: |
    Transmission provides a simple and easy to use cross-platform lightweight BitTorrent client
networking : yes # check
builddeps  :
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(libcurl)
    - pkgconfig(libevent)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc/transmission/news
check      : |
    %ninja_check
