name       : transmission
version    : '2.94'
release    : 14
source     :
    - https://github.com/transmission/transmission/archive/2.94.tar.gz : 440c2fd0f89b1ab59d8a4b79ecd7bffd61bc000e36fb5b6c8e88142a4fadbb1f
license    : GPL-2.0-or-later
component  : network.download
summary    : Lightweight BitTorrent client
description: |
    Transmission provides a simple and easy to use cross-platform lightweight BitTorrent client
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcurl)
    - pkgconfig(libevent)
setup      : |
    %autogen --with-gtk
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
