name       : transmission
version    : 2.92
release    : 4
source     :
    - https://github.com/transmission/transmission-releases/raw/master/transmission-2.92.tar.xz : 3a8d045c306ad9acb7bf81126939b9594553a388482efa0ec1bfb67b22acd35f
license    : GPL-2.0
component  : network.download
summary    : Lightweight BitTorrent client
description: |
    Transmission provides a simple and easy to use cross-platform lightweight BitTorrent client
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libevent)
setup      : |
    %configure --with-gtk
build      : |
    %make
install    : |
    %make_install
