name       : transmission
version    : '3.00'
release    : 18
source     :
    - https://github.com/transmission/transmission/releases/download/3.00/transmission-3.00.tar.xz : 9144652fe742f7f7dd6657716e378da60b751aaeda8bef8344b3eefc4db255f2
license    : GPL-2.0-or-later
component  : network.download
summary    : Lightweight BitTorrent client
description: |
    Transmission provides a simple and easy to use cross-platform lightweight BitTorrent client
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcurl)
    - pkgconfig(libevent)
setup      : |
    %autogen --with-gtk
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
