name       : transmission
version    : '2.94'
release    : 11
source     :
    - https://github.com/transmission/transmission/archive/2.94.tar.gz : 35442cc849f91f8df982c3d0d479d650c6ca19310a994eccdaa79a4af3916b7d
license    : GPL-2.0-or-later
component  : network.download
summary    : Lightweight BitTorrent client
description: |
    Transmission provides a simple and easy to use cross-platform lightweight BitTorrent client
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcurl)
    - pkgconfig(libevent)
setup      : |
    %configure --with-gtk
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
